export interface Recruiter {
  id: string
  name: string
  company: string
  title: string
  location: string
  niche: string[]
  experience: string
  bio: string
  specialties: string[]
  rating: number
  placements: number
  avatar?: string
  verified: boolean
}

export const mockRecruiters: Recruiter[] = [
  {
    id: "1",
    name: "Sarah Chen",
    company: "TechTalent Solutions",
    title: "Senior Technical Recruiter",
    location: "San Francisco, CA",
    niche: ["Engineering", "Product"],
    experience: "8 years",
    bio: "Specializing in placing top-tier engineers at fast-growing startups and established tech companies.",
    specialties: ["Frontend", "Backend", "Full Stack", "DevOps"],
    rating: 4.9,
    placements: 150,
    verified: true,
  },
  {
    id: "2",
    name: "Michael Rodriguez",
    company: "Design Recruiters Pro",
    title: "Creative Talent Specialist",
    location: "New York, NY",
    niche: ["Design", "Product"],
    experience: "6 years",
    bio: "Connecting exceptional designers with companies that value creativity and innovation.",
    specialties: ["UI/UX Design", "Product Design", "Design Systems"],
    rating: 4.8,
    placements: 120,
    verified: true,
  },
  {
    id: "3",
    name: "Emily Watson",
    company: "Remote First Recruiting",
    title: "Remote Talent Advisor",
    location: "Remote",
    niche: ["Engineering", "Remote"],
    experience: "5 years",
    bio: "Expert in remote placements across time zones. Helping companies build distributed teams.",
    specialties: ["Remote Work", "Distributed Teams", "Time Zone Management"],
    rating: 4.7,
    placements: 95,
    verified: true,
  },
  {
    id: "4",
    name: "David Kim",
    company: "Executive Search Partners",
    title: "Executive Recruiter",
    location: "Seattle, WA",
    niche: ["Leadership", "Engineering"],
    experience: "12 years",
    bio: "Placing C-level executives and senior engineering leaders at high-growth companies.",
    specialties: ["C-Suite", "VP Engineering", "Technical Leadership"],
    rating: 4.9,
    placements: 200,
    verified: true,
  },
  {
    id: "5",
    name: "Jessica Martinez",
    company: "Startup Recruiters",
    title: "Startup Talent Partner",
    location: "Austin, TX",
    niche: ["Startups", "Product"],
    experience: "7 years",
    bio: "Helping early-stage startups build their founding teams and scale their organizations.",
    specialties: ["Early Stage", "Product Management", "Growth"],
    rating: 4.6,
    placements: 110,
    verified: false,
  },
  {
    id: "6",
    name: "Robert Thompson",
    company: "Data Science Recruiters",
    title: "Data Talent Specialist",
    location: "Boston, MA",
    niche: ["Data Science", "Engineering"],
    experience: "9 years",
    bio: "Connecting data scientists and ML engineers with companies solving complex data challenges.",
    specialties: ["Machine Learning", "Data Engineering", "Analytics"],
    rating: 4.8,
    placements: 140,
    verified: true,
  },
  {
    id: "7",
    name: "Amanda Foster",
    company: "Marketing Talent Hub",
    title: "Marketing Recruiter",
    location: "Chicago, IL",
    niche: ["Marketing", "Growth"],
    experience: "5 years",
    bio: "Specializing in marketing roles from entry-level to VP, across all marketing disciplines.",
    specialties: ["Growth Marketing", "Content Marketing", "Brand"],
    rating: 4.5,
    placements: 85,
    verified: false,
  },
  {
    id: "8",
    name: "James Wilson",
    company: "Security Recruiters",
    title: "Security Talent Advisor",
    location: "Washington, DC",
    niche: ["Security", "Engineering"],
    experience: "10 years",
    bio: "Placing security engineers and cybersecurity professionals at companies prioritizing security.",
    specialties: ["Cybersecurity", "Security Engineering", "Compliance"],
    rating: 4.9,
    placements: 160,
    verified: true,
  },
  {
    id: "9",
    name: "Lisa Anderson",
    company: "Finance & Operations Recruiters",
    title: "Finance Recruiter",
    location: "Remote",
    niche: ["Finance", "Operations"],
    experience: "6 years",
    bio: "Helping finance and operations professionals find their next role at innovative companies.",
    specialties: ["FP&A", "Accounting", "Operations"],
    rating: 4.6,
    placements: 100,
    verified: false,
  },
  {
    id: "10",
    name: "Chris Park",
    company: "Mobile Talent Specialists",
    title: "Mobile Recruiter",
    location: "Los Angeles, CA",
    niche: ["Mobile", "Engineering"],
    experience: "4 years",
    bio: "Connecting mobile developers with companies building the next generation of mobile apps.",
    specialties: ["iOS", "Android", "React Native", "Flutter"],
    rating: 4.7,
    placements: 75,
    verified: true,
  },
]
